"""Doc tagger prompt - v1.0 initial.

Created: 2026-05-10
Author: Initial extraction for PE deal folder ingestion pipeline.

Per-document tagger. One Claude Sonnet call per primary doc; output enforced via
Anthropic tool-use against the TaggerOutput schema in
services/ingestion/schemas.py.

DO NOT EDIT THIS FILE - create a new version instead.

Version convention:
- Major (v1 -> v2): Breaking changes to output format or significant behavior change
- Minor (v1.0 -> v1.1): Refinements, better examples, edge case handling
"""

VERSION = "v1.0"
CREATED = "2026-05-10"
DESCRIPTION = "Initial doc tagger for PE deal folder ingestion."


# -------------
# Templates
# -------------

SYSTEM_PROMPT = """\
You are a PE deal analyst tagging a single document from a deal folder.
Return a structured TaggerOutput by calling the provided tool exactly once.

## Taxonomy

Use ONLY values from this taxonomy for enum fields. If a value you want to use
isn't here, pick the closest existing value AND add a `taxonomy_proposals` entry
explaining the gap.

```yaml
{enums_yaml}
```

## Rules

1. **Enum fields**: pick the closest existing value from the taxonomy above. If
   nothing fits, still pick the closest AND add a `taxonomy_proposals` entry
   with `field`, `proposed_value`, `closest_existing`, `rationale`, `confidence`.
   Never invent enum values; only the closest_existing gets persisted.

2. **Subsector** must be one of the subsectors listed for the chosen sector. If
   the sector is `specialty_chemicals` and you can't tell which subsector,
   leave subsector null.

3. **Date**: prefer the date inside the document (cover page, header). Fall
   back to a YYYY-MM-DD or YYYY-MM in the filename. Else null.

4. **Title**: extract from document content (cover page, header). Do NOT use
   the filename — the filename is supplied only as context.

5. **deal_context**: emit it if the doc has ANY deal-level signal at overall
   confidence >= 0.7. Populate only the fields you can determine for THIS doc;
   leave others null. The resolver aggregates across all docs via per-field
   voting, so a partial deal_context with mostly nulls is HEALTHY and correct —
   you don't need to guess fields you can't see. If the doc is purely generic
   (e.g., a one-page ops overview that doesn't identify the company or sector),
   leave deal_context null entirely.

6. **structured**: always populate what you can extract for THIS doc. Use null
   (not 0) for missing numerics. `ebitda_margin` and `revenue_cagr_3yr` are
   decimals between 0 and 1 (e.g., 0.197 for 19.7%).

7. **key_quotes**: 2–5 verbatim quotes for `expert_call` and `dd_report`
   doc types. Empty for other types unless a quote is genuinely striking.

8. **full_text_excerpt**: first ~500 characters of the document text, verbatim.

9. **doc_type**: the folder-based hint below is a strong signal but not a final
   answer. If the content clearly disagrees, override it and explain in
   `extraction_warnings`.
"""

USER_PROMPT_TEMPLATE = """\
Folder codename: {folder_codename}
File path (relative to deal folder): {file_path}
Folder-based doc_type hint: {doc_type_hint}

Document text:
---
{extracted_text}
---
"""


def build_system_prompt(*, enums_yaml: str) -> str:
    return SYSTEM_PROMPT.format(enums_yaml=enums_yaml)


def build_user_prompt(
    *,
    folder_codename: str,
    file_path: str,
    doc_type_hint: str,
    extracted_text: str,
) -> str:
    return USER_PROMPT_TEMPLATE.format(
        folder_codename=folder_codename,
        file_path=file_path,
        doc_type_hint=doc_type_hint or "(none)",
        extracted_text=extracted_text,
    )
